### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by andgarzonmal** [ElsonOtake/Catalog_of_my_things#43]
1. Link to project 

- https://github.com/ElsonOtake/Catalog_of_my_things/projects/1

2. There are four people in our team  
- Team member # 1 @andgarzonmal 
- Team member # 2 @fibini 
- Team member # 3 @Andyveloper 
- Team member # 4 @ElsonOtake

**Comment by sja-thedude** [comment]
## Project Approved 👍 

Hi Team, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights:
- All requirements completed

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
